FP-0013 pagination
TesaRocks/final-project-front-end pull request #7
Opened 2021-06-25 21:09 UTC by TesaRocks

Hi Diego, please have a look at my PR
Once you agree, I can implement the same logic to UserList component.

I did it mostly by myself since I could not find many suitable answers on the web.

Regards

Alexis

2021-06-30 21:00 UTC, diegolaciar requested changes
hi @TesaRocks,

This PR is huge! 
And it will be very affected by the change of the invoice model.
Please work on that, then send a new PR.

Cheers,
Diego

2021-06-30 21:00 UTC, diegolaciar commented on src/app/invoice/invoice.component.html
> +    <mat-card class="product-card">
I dont get what is this component.

2021-06-30 21:00 UTC, diegolaciar commented on src/app/aplication-state.ts
> +  invoiceDetailState: IInvoiceDetailInitialState;
I don't like this idea, this is not a good design
You should handle all the invoices and the detail in ONE model.

2021-07-07 14:02 UTC, TesaRocks commented on src/app/aplication-state.ts
> +  invoiceDetailState: IInvoiceDetailInitialState;
done thnaks

2021-07-07 14:02 UTC, TesaRocks commented on src/app/invoice/invoice.component.html
> +    <mat-card class="product-card">
fixed thanks

2021-07-08 16:23 UTC, merged